[package]
name = "staking-io"
version = "0.1.0"
edition = "2021"

[dependencies]
gmeta = { git = "https://github.com/gear-tech/gear", branch = "stable" }
gstd = { git = "https://github.com/gear-tech/gear", branch = "stable", features = ["debug"] }
scale-info = { version = "2", default-features = false }
parity-scale-codec = { version = "3", default-features = false }
