[package]
name = "staking-io"
version = "0.1.3"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear", features = ["debug"], branch = "testnet" }
gmeta = { git = "https://github.com/gear-tech/gear", branch = "testnet" }
scale-info = { version = "2", default-features = false }
parity-scale-codec = { version = "3", default-features = false }
