[package]
name = "staking-state"
version = "0.1.3"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear", features = ["debug"], branch = "testnet" }
gmeta = { git = "https://github.com/gear-tech/gear", features = ["codegen"], branch = "testnet" }
staking-io = { path = "../io" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear", features = ["metawasm"], branch = "testnet" }
